---
title: "Intermezzo I"
---

The focus of the first workshop of this course has been version control, and an introduction to Git. Some very important Git
workflows have been covered, such as the "modify-add-commit" cycle. However, all the Git topics covered then
were focusing on creating and using a `local` repository, stored on the user's workstation, and with only one
participant - the user herself.

In this second workshop we will take you to the next level in terms of Git functionality - and show you how you can
fully harness the power of version control by using Git in a collaborative environment where multiple users can
work together on the same project all coordinated through Git workflows. Once we master such advanced Git workflows,
we will pivot towards the programming part of this course by looking at Python virtual environments.

To summarize, this is how this second workshop will be organized:

- GitLab - an on-line Git platform
- Short break
- Advanced Git Commands - facilitated by on-line Git platforms such as GitLab
- Lunch break
- Python Virtual Environments

### Required Software {#required}

In addition to the software we were using in the previous workshop, for today you will also need the following:

1. **[Python]** (3.12 recommended)
2. Access to the **[TUD GitLab]**

[Python]: https://www.python.org/
[TUD GitLab]: https://gitlab.tudelft.nl/users/sign_in
